config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :authors, only: :show
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  name       :string
#  hometown   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Author < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  author_id   :integer
#

class Post < ActiveRecord::Base
  belongs_to :author

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @author = @post.author
  end

  def new
    @post = Post.new
  end

  def create
    @author = Author.first
    @post = Post.new
    @post.title = params[:title]
    @post.description = params[:description]
    @post.author_id = @author.id
    @post.save
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(title: params[:title], description: params[:description])
    redirect_to post_path(@post)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_author.erb
<%= @author.name %>
<%= @author.hometown %>

app/views/authors/_author.html.erb
<%= @author.name %>
<%= @author.hometown %>

app/views/authors/_authors.html.erb
<%= @author.name %>
<%= @author.hometown %>

app/views/authors/_form.html.erb
  <label>Author Name:</label><br>
  <%= text_field_tag :name, @author.name %><br>

  <label>Author's Hometown</label><br>
  <%= text_area_tag :hometown, @author.hometown %><br>
  
  <%= submit_tag "Submit Author" %>

app/views/authors/edit.html.erb
<h3>Author Form</h3>

<%= form_tag author_path(@author), method: "put" do %>
  <%= render "form" %>
<% end %>

app/views/authors/index.html.erb
<% @authors.each do |author| %>
  <div><%= author.name %></div>
<% end %>

app/views/authors/new.html.erb
<%= form_tag authors_path do %>
  <%= render "form" %>
<% end %>

app/views/authors/show.html.erb
<%= render 'author' %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogFlash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_edit_new.html.erb
<label>Post title:</label><br>
<%= text_field_tag :title, @post.title %><br>

<label>Post Description</label><br>
<%= text_area_tag :description, @post.description %><br>
<%= submit_tag "Submit Post" %>

app/views/posts/_form.erb
<label>Post title:</label><br>
<%= text_field_tag :title %><br>

<label>Post Description</label><br>
<%= text_area_tag :description %><br>

<%= submit_tag "Submit Post" %>

app/views/posts/_form.html.erb
<label>Post title:</label><br>
<%= text_field_tag :title, @post.title %><br>

<label>Post Description</label><br>
<%= text_area_tag :description, @post.description %><br>
<%= submit_tag "Submit Post" %>

app/views/posts/_partial.html.erb
<label>Post title:</label><br>
<%= text_field_tag :title, @post.title %><br>

<label>Post Description</label><br>
<%= text_area_tag :description, @post.description %><br>

<%= submit_tag "Submit Post" %>

app/views/posts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Layouts and Templates in Rails Lab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Flatiron Widgets: Admin</h1>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h3>Post Form</h3>

<%= form_tag post_path(@post), method: "put" do %>
  <%= render "form" %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div><%= post.title %></div>
<% end %>

app/views/posts/new.html.erb
<%= form_tag posts_path do %>
  <%= render 'form' %>
<% end %>

app/views/posts/show.html.erb
<%= render 'authors/author' %>


<h1><%= @post.title %></h1>
<p><%= @post.description %></p>